version: "3.8"

services:
  # Serviço da API
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      # AQUI: Atualize a string de conexão para usar as novas variáveis
      - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=${DB_DATABASE};User=${DB_USER};Password=${DB_PASSWORD};
      - Jwt__Key=${Jwt__Key}
      - EMAIL_SMTP_SERVER=${EMAIL_SMTP_SERVER}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_FROM_NAME=${EMAIL_FROM_NAME}
      - EMAIL_FROM_ADDRESS=${EMAIL_FROM_ADDRESS}
    depends_on:
      - db
    networks:
      - app-network

  # Serviço do Banco de Dados
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      # AQUI: Use as variáveis do .env para configurar o MySQL
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
